### ISSUE TITLE
threadpool_wait() function?

### ISSUE THREAD

**Issue by fgvieira** [mbrossard/threadpool#4]
Hi,

I've just tried this thread pool and it seems to work pretty well. However, I was wondering if there is a way to wait for all threads to finish without actually freeing the memory (so that the pool is still usable).

I'm implementing a method that performs several sequential analyses (where each depends on the result of the previous) and, since it is a bit slow, I'd like to thread each analysis. So, ideally, I'd create the thread pool in the beginning, launch all tasks for the first analysis and wait for all tasks to finish. Then, I'd process the results and launch the jobs of the next analysis (and so on). Is it possible?

**Comment by fgvieira** [comment]
Hi xnox,

thanks for your reply but from what I understand from the code, using the threadpool_graceful flag will just wait for all tasks to finish before destroying the queue (as opposed to destroying it and killing all running tasks). But in my case, I want to re-use the queue for more analyzes....

In the end I created a function to just wait for all jobs to finish:

```C
int threadpool_wait(threadpool_t *pool, unsigned int wait_time)
{
  bool wait = true;

  while(wait) {
    // Sleep for wait_time miliseconds
    struct timespec wait_time_t = {0};
    wait_time_t.tv_sec = 0;
    wait_time_t.tv_nsec = wait_time * 1000000L;
    nanosleep(&wait_time_t, (struct timespec *)NULL);

    if(pthread_mutex_lock(&(pool->lock)) != 0)
      return threadpool_lock_failure;

    if(pool->count == 0 &&
       pool->run_thread_count == 0)
      wait = false;

    if(pthread_mutex_unlock(&(pool->lock)) != 0)
      return threadpool_lock_failure;
  }
  
  return 0;
}
```

Comments are welcome! :)
FGV

**Comment by sunwake** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到
